branch-defaults:
  master:
    environment: ens-testing-dev
global:
  application_name: ens-testing
  default_ec2_keyname: null
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-west-2
  profile: eb-cli
  sc: git
