branch-defaults:
  master:
    environment: ensDJango-env
global:
  application_name: ens-django
  default_ec2_keyname: MikeD3
  default_platform: Python 3.4 (Preconfigured - Docker)
  default_region: us-west-2
  profile: eb-cli
  sc: git
